apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:niVDU/DUAVQPpvYryCeMKprZy/n6EdEUlVZE4c/+jn/F2Pwy+hdo/g==,iv:dj9630uV55MZTkXldO33X6HHwOaisQAG8C4iitxJMM8=,tag:B2674qqFXMCu2+h7yXKi+Q==,type:str]
sops:
  age:
    - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TTR6V3ByYW95ZmhOUjd6
        YW5DMmU4NjQ0ZkNPSTdTZGM5OTRuaUc2em1BCkpaWXgzbk9aOVRYb01XUC9pREhr
        SWRkWDg3WjRWbVZoa1pQcHl1akZxTTAKLS0tIFo1dEY5bk1CVlBSWmlOQmNOZDl2
        MDk0Z2JhLzdtM3B3UDBVR0crSW9TdWMK1PK+yoMLqRWiJjoSU2ssO9ntpVrjReGk
        1uakEY4eyCeeqgggR9w9j9gv4uRPsqI2GdoZ3HiUIesIIxpp0dtPyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T02:54:45Z"
  mac: ENC[AES256_GCM,data:xwJJnwSiENISkqpCrBR4QEG8tuGDBHEQZWusWh5HVPK5Xktt1KhpWg67bIuRMA9rKfddWd5PdOQ+sjHLuUZymzkC2A9rNk7Aa1lEN8t+SNntAnoA6F7l9nUWaDPvTg42ogG3qoIz+b7CG5hmjUZEx+EfwlkH8sKhR046sPOh6Rw=,iv:+T5MWjZM4z+l+1Fw4s/gxLRjCOLBMGd11DUkITz/IU8=,tag:qR6pcPWIS0eMOHv7uJICWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
