---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app.yaml
  - secret.yaml
  - httproute.yaml

configMapGenerator:
  - name: authentik-values
    namespace: authentik
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
