apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:qMiqZM/IlCV9obOMxUQvbKlXxCfZ9amtrb7Dq2B1vQhqlk5xyscrn6REGJUukT2a5MI=,iv:sYkljzVZMLltcXPXf2rAGiIhAGL/Iq3zZFU99eThNd0=,tag:2hiHe9QgL/DYZPBlH0EMSw==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:xKwQSH/VJWeGAAnoVOsqr8SE8hgBJCuPrPgEWJltQsp89rgozFwb7j4UOsQ=,iv:SIHsFWWqA4/dCzBJcdZVcr0RDFc85JhfZi96HT8IaXA=,tag:5KZbMfx9hJTQyujwyRJLug==,type:str]
  password: ENC[AES256_GCM,data:3abyjIrpo53dq8F5gc0DF2Kv8u1fAULYnnnZT6xJkozAhnVFzcOoTBD+icU=,iv:rF1Dsu64YUCy8RdMwUakNqiToaPD19NmlRWXbU4lpSE=,tag:zC8ip+hhiM3F1iBrzH+ZBw==,type:str]
  AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:QwyCpJxrX0QlRWrjiZ7V5ygJ695o,iv:MVcJBvFushv9YgadEcmZ5VfQHY/nhsrPlqmBF+8TqZk=,tag:Vk2443D5DJcSJWJWsOHLbQ==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:JHc6xkDwpoMs+fe2sxmgnsuIsQRSRUuhNBfdGkLktykGFBb6pSygaMv4xPw=,iv:gh+xWO5IaY1xajoEMeBRImbYCxjv1rH9QO0kZos7x1E=,tag:s/um89GWSiKwK2saUoqxog==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:7HcVgWEa61n4J/dWaAlFbpPhOtacF6NY2hE5TtCh11bEhn+EIxSr9ix09d4=,iv:BwzyLhT5WMXag1JBvb+2QbdMJRtW6WJfrPuRUVmbt64=,tag:KS5EP9SqCX2FWtTDGDrxoA==,type:str]
sops:
  age:
    - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aGQ5ZHFsMkhwMUkxRDl4
        ZnZtUW9PSFBobEIxRDd1SjVlLys5L0paandrCk5OR2ZLRmdkZUxmRjlMVlZ2TWY4
        WDc4dFJGbEFUbDU4dGIwd2gvL1NvNmMKLS0tIFZDNlhTdTdFS2x0enhSNGEyOTJW
        anAzenV5T2Y4OE5va2p1blo1ZGsrQjAKLD55XpvDimvfMbO3qtqXRXzgorg9vRlZ
        n2yI1xA/z+SqMmseYgQiFYhtGH7MNkv/rr96F8HKQ3NjQaVUBcbNfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T05:37:59Z"
  mac: ENC[AES256_GCM,data:6zTVtOZkxN4qsMyhgSpbkgbFBQmiV4+DIVHKkTFsvOyRRjSQ5xRoGMnaMpZixipVK4lfHrYYPxN+yUZ9EBJO+7DFMGCSc6D724H5s9UZz5VbvZJkkY/K5EWNXjGeOF3ANs6b3sFkZ8W1luYvtJVK45s2AijzQIQM5bFY3E7qM5g=,iv:Y1Mk+317RqM/0mOjKRShwxilIQ/PO9Hr9f68mMTZxdM=,tag:gbXB/46fOyRbu3819zlMhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
