apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:CdE7eVHKnL+APDXHZLyzsavUglFW+SBVHxaO7vwOCPWo+7Ojb7IhhwDUKB8eySNk/GA=,iv:HZQCOi6LC+OuXie+iJ7NWQFckP26TIjFNQwJpd4rXEI=,tag:pRX84MkpSv6tb46xt0udKg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:m9MZs8EWzraJPAHxF8WyyPAl44eONLTQteulxYcrv7cGTLbGpyidFoLQbXY=,iv:hsXt2XyrWYfTc2DqxgEhll0/zCFWP3QNBmHFLBLOZM0=,tag:8/RzYqPh0Av3NRLri5PVzA==,type:str]
    password: ENC[AES256_GCM,data:gQvtpFOPA6oH4uJERF2wmlyiaPhN+1VfA/KQpD3H/uaayAQMmINq9qy5tsY=,iv:cnmngHJoIz803reb5xPWMHdqnhsTTCED2flUh7HBclk=,tag:IvaMn2oNER9aMlRSlb2mNA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:7gjoGpUXOYKcX2mvY7rcMvwGxEVr,iv:qOQNZpTK00kWSn7vdLqaRU2vzyBOjz9P4Zi2o9DYhps=,tag:QqdOOcoel42XgJacav0xCQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:ksKvzUWz22eP96PceMKzh2czpJmdF3GvGlWWSO5QfTTVa9HBspcxjPfJKqw=,iv:jjdzrfXE9Jxg3nDfumFcQYS4evrGz2TUK6lPpDqYZSQ=,tag:ghMAu/dhZ8uv0rEYDs0WIw==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:oJDQu6F6l7wOp1vp/GOM3QwdS0s23Xcg5nnAjou4LOe9AgxD3V2ibrkKQkY=,iv:MR3q9pHqSWPHXE6L9mqZOAq3iyCYCpFcN00LFE0zVqU=,tag:BWhm20qEZNC+9yX1I11ACQ==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ouwdCzLNVuEWCy9IxNOE3OslV5c2v+QP3d3R30dj/biIfLUVN6JHaLCW9Hk=,iv:e2yqT7v7aPXimR58D0W/W7h/pPx6q49MM9/ADXO1Y24=,tag:redPch785bWj4I8NzwdkAw==,type:str]
sops:
    age:
        - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UmQvdGZTbTZ6am1hdGg2
            NEFYYnN3aTVvTlVKZzNGSXNCWWJOSE9nM1N3Ck5BWWRyczF1YlYvNHRBS011SlIx
            S09taFlPRmQ0alZHdkMweFdWNVl5Qk0KLS0tIERwOXdaWkNBRkp1S0F2R1hxQjMz
            Q0tBWllzZkFZR3VuTXJlN3V0ZWl4cHcKmzI5pPza/qn15zY85GPLNlpEsXyc0vN1
            pUGasUW2DJj3lzAWl+uPmn5J+eDtIeldGyv3W0UM+0tLX3mK6cp1yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T18:24:48Z"
    mac: ENC[AES256_GCM,data:OPNDiV8HiHpZRuGiAH/P+wEGzKBaLxr9L7nTGNgpOI44NvHIprlBNhjVvGLz3WVaDf/KUztA9Vvf6/MmsaefSDpMZS2/e4sM60rQM8JMKCGHuMdzrf/1gyCXhkpa43MGbnNnNy3UOhOhOrfHITr7I326DBAH1N4l/jCTDF0WzlQ=,iv:Gv98Ufk4onG/I9j3Z/TiJiPO+Vo/znUXU5WL81MUX7w=,tag:FPoOCWtu4QHTFHeAaJRdTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
