---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  dependsOn:
    - name: loki
    - name: mimir
  interval: 5m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: grafana
      version: 11.0.1
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
  values:
    envFromSecret: grafana-env
    admin:
      existingSecret: grafana-credentials
    grafana.ini:
      server:
        domain: monitoring.lab.petebeegle.com
        root_url: https://monitoring.lab.petebeegle.com
      auth.generic_oauth:
        enabled: true
        name: Authentik
        client_id: grafana
        client_secret: $__file{/etc/secrets/oauth-client-secret}
        scopes: openid email profile groups
        auth_url: https://authentik.lab.petebeegle.com/application/o/authorize/
        token_url: https://authentik.lab.petebeegle.com/application/o/token/
        api_url: https://authentik.lab.petebeegle.com/application/o/userinfo/
        role_attribute_path: contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
        allow_sign_up: true
    extraSecretMounts:
      - name: oauth-client-secret
        secretName: grafana-credentials
        defaultMode: 0440
        mountPath: /etc/secrets
        readOnly: true
    sidecar:
      dashboards:
        enabled: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: loki
            uid: loki
            access: proxy
            basicAuth: false
            editable: true
            jsonData:
              tlsSkipVerify: true
            orgId: 1
            type: loki
            url: http://loki-gateway
          - name: prometheus
            uid: prometheus
            access: proxy
            basicAuth: false
            editable: true
            jsonData:
              tlsSkipVerify: true
            orgId: 1
            type: prometheus
            url: http://mimir-nginx/prometheus
    alerting:
      contactpoints.yaml:
        apiVersion: 1
        contactPoints:
          - name: discord
            orgId: 1
            receivers:
              - uid: discord-webhook
                type: webhook
                settings:
                  url: "http://pretty-discord-alerts.monitoring.svc.cluster.local:80/webhook"
      policies.yaml:
        apiVersion: 1
        policies:
          - orgId: 1
            receiver: discord
            group_by: ["alertname", "namespace"]
            group_wait: 10s
            group_interval: 5m
            repeat_interval: 12h
            routes:
              - receiver: discord
                matchers:
                  - component = valheim
                group_by: ["player"]
                group_wait: 0s
                group_interval: 1m
                repeat_interval: 1m
                send_resolved: false
              - receiver: discord
                matchers:
                  - severity =~ "warning|critical"
