---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - secret.yaml
  - folders.yaml
  - grafana-env.yaml
  - gateway.yaml
  - grafana-instance.yaml
  - dashboards
  - alerting
