---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: flux-dashboard
    namespace: monitoring
    files:
      - dashboard.json=config/flux-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: kubernetes-dashboard
    namespace: monitoring
    files:
      - dashboard.json=config/kubernetes-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: proxmox-dashboard
    namespace: monitoring
    files:
      - dashboard.json=config/proxmox-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
resources:
  - app.yaml
  - secret.yaml
  - grafana-env.yaml
  - gateway.yaml
