apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:5DX/Nnw=,iv:Ymk32eDk2u7kT1q6pcPqVT2KMLcnMk6eK9ctCLw5VOg=,tag:15c7q7JJ4s3kV4NI2twuIw==,type:str]
    admin-password: ENC[AES256_GCM,data:PJhS0SgTzd7YNlr7jyhVX5pVuhw=,iv:Ii+Ld5zaFy25pAdyaD7rMVTFiP7hpsEgUI8VMwsIC0I=,tag:oBvv2a7sOzW+PIkc0W6b4Q==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:XhputVMdiIqmlgDZkyjX7Hxb2I31E5xaPKCdhQXnKQ6PSNIzItiycJQ75cs=,iv:4Y1LI0KHVf0xNPHwnoF+XKlT2EH+tyyFTbaQkRqbz1s=,tag:j8iamoIovdE9xw8+zNSG9g==,type:str]
sops:
    age:
        - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZncrUmU5alZuUU1DZWRN
            b0lMU3VIZms1eURmYUlUN3VNeDdHUW1wL0gwCi9qVkZZODdKdkJOWlZKODdzY3FQ
            Ky9ybU4zZUx3bTJYTk1LWVBlOUpjUU0KLS0tIDVJQmxsOXFENUE1V0c1eE9FczRQ
            cVNHZmtNM2d5Zjd1ZnpidmpYc0pnOGsKo24x/VnWi5/8jMcwe4ubFhZGvob1sos3
            pAJjqt8yiZAC76KrbEJ4EgS/wbSO7muavXBnpnZRKaafjnzp5Ym/hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T18:13:15Z"
    mac: ENC[AES256_GCM,data:8nl8AwHYpakhcMsHR0eC1UA3+lBZWLyrc8lgBaNSLw3TY+qaivfhs7W6Swx8dlx9sjxMaAtgZNXw7q1b1cFuCXTaFh5NdSXfgwPpxcHMtBbiqTbR6mv/6Q9qPUl/IorcEtu9X+hmR98bxaSW7gJQVkVAQEqv7mp2iE+I6TAWHu4=,iv:12rQ7JDW0SM5qk1VB1cbCJeK/JRFuRuBFmV4W56ElGM=,tag:tqXz23ll1vkiyVRthTvPuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
