---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: kube-system
spec:
  url: https://grafana.github.io/helm-charts
  interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator-crds
  namespace: kube-system
spec:
  interval: 5m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: grafana-operator
      version: v5.16.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: kube-system
  values:
    # Only install CRDs, not the operator itself
    operator:
      enabled: false
