---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repositories.yaml
  - loki
  - mimir
  - kube-state-metrics
  - alloy
  - grafana
  - snmp-exporter
  - otel-collector
