---
apiVersion: v1
kind: Service
metadata:
  name: synology
  namespace: external
spec:
  ports:
    - name: https
      protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: synology
  namespace: external
  labels:
    kubernetes.io/service-name: synology
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 5001
endpoints:
  - addresses:
      - 192.168.30.99
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: synology-route
  namespace: external
spec:
  parentRefs:
    - name: passthrough
      namespace: gateway
  hostnames:
    - synology.petebeegle.com
  rules:
    - backendRefs:
        - name: synology
          port: 5001
