# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

configMapGenerator:
  - name: grafana-oauth-blueprint
    files:
      - grafana-oauth.yaml
  - name: synology-oauth-blueprint
    files:
      - synology-oauth.yaml
