---
apiVersion: v1
kind: Namespace
metadata:
  name: renovate
  labels:
    app.kubernetes.io/component: renovate
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: renovate
  namespace: flux-system
spec:
  interval: 12h
  url: https://docs.renovatebot.com/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 1h
  releaseName: renovate
  chart:
    spec:
      chart: renovate
      version: 43.15.0
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
  values:
    renovate:
      platform: "github"
      endpoint: "https://api.github.com/"
      existingSecret: renovate
      config: |
        {
          "platform": "github",
          "repositories": ["petebeegle/homelab"],
          "baseBranches": ["main"],
        }
    envFrom:
      - secretRef:
          name: renovate-secret
