---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: ksm-config
    namespace: monitoring
    files:
      - values.yaml=config/metrics.yaml
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yaml
resources:
  - app.yaml
