---
apiVersion: v1
kind: Namespace
metadata:
  name: valheim
  labels:
    name: valheim
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: valheim-k8s
  namespace: flux-system
spec:
  interval: 12h
  url: https://addyvan.github.io/valheim-k8s/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valheim-server
  namespace: valheim
spec:
  interval: 5m
  releaseName: valheim-server
  chart:
    spec:
      chart: valheim-k8s
      sourceRef:
        kind: HelmRepository
        name: valheim-k8s
        namespace: flux-system
      version: "2.0.1"
  values:
    worldName: beleriand
    serverName: arda
    passwordSecret: valheim-secret
    networking:
      serviceType: LoadBalancer
      loadBalancerIP: 192.168.3.251
    storage:
      kind: persistentVolumeClaim
      pvc:
        size: 25Gi
    serverStorage:
      kind: persistentVolumeClaim
      pvc:
        size: 25Gi
