---
apiVersion: v1
kind: Namespace
metadata:
  name: dataplane
  labels:
    app.kubernetes.io/component: dataplane
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi-chart
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://zebernst.github.io/synology-csi-talos
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: dataplane
spec:
  interval: 5m
  releaseName: synology-csi
  chart:
    spec:
      chart: synology-csi
      sourceRef:
        kind: HelmRepository
        name: synology-csi-chart
        namespace: flux-system
      version: "0.9.5-pre.4"
  values:
    clientInfoSecret:
      create: false
      name: synology-csi-secret
    storageClasses:
      synology-iscsi-storage:
        disabled: true
        isDefault: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        parameters:
          location: /volume2
          fsType: "btrfs"
          dsm: 192.168.3.27
          formatOptions: "--nodiscard"
      synology-nfs-storage:
        disabled: false
        isDefault: true
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        parameters:
          protocol: nfs
          location: /volume2
          dsm: 192.168.3.27
          fsType: ext4
          mountPermissions: "0755"
          mountOptions: "nfsvers=4.1"
    volumeSnapshotClasses:
      synology-iscsi-snapshot:
        disabled: true
        deletionPolicy: Delete
