apiVersion: v1
kind: Secret
metadata:
  name: synology-csi-secret
  namespace: dataplane
type: Opaque
stringData:
  client-info.yml: ENC[AES256_GCM,data:mIJ47/9HluwCLApWv5tKxnJKeUR0Ag8D4H1Qv9X4BWVtV+04A1oJ1DuK7zOhpENM4g1NPMtfs0YcGPViudC2w9gZgi21SDrwWT+MSoU1s/VLv57IvodYfjxNrOfeCs0o81qjJ3TueOATK+gh55U4q+79jePYMsmt9Ige3HIGB9geCHydYTSJptbepO92dwYPCrnLzhChUeJlpRA+S3thD9k3UxWTyxPRNbd0h+PmWRVkuClXbMvg6C55phXTv48xgdE/939mwMmLd+QGXFgn9lGssZyVpwdZm8gxCUaeNqInAy1BZoZ9pA==,iv:CNBZVz1ud3lO6+jM3oHHHmGkUQnKEpvUXIriDUruAEk=,tag:kQEfSowBg1Fp33SuzA1z6w==,type:str]
sops:
  age:
    - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ampuZnRwaGtrYTBIQ2VD
        ZllVdHcwYnlBL1NWd0lBY0NlUEJQRlkrejNVCmV1aEtlc3Z4UXFwMkpBQlQ1QkVL
        cDRWV0pTYkhuY05OZlRRenh3ZUlpM1kKLS0tIDlFRVpZaFY4WUlVQ1NlZTdyZk1r
        cmgrRmtoSTZyS1pZNnI2TEw4VUxYVWMKaMFpQQY99bc5vJsqrUFOunReHw6XZljF
        mUWLaVYTi1UhgRcV8uwyl5SHsk1mg8fqiK22PV28rLiQA8ioDhWdiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:27:27Z"
  mac: ENC[AES256_GCM,data:v6a0tkSmr/PJK74sp7m6ifH8/t8kVGmtUUXa24NSIc6Dyb/JFbDswm7bZG2mmp9Eiaj4lqektjplpAtwMTWn2HP8NkKponDh+uESOGU73PMnZPmCrrmdZ/wS56vvzjRMenlROmzAdPe4Lo+dWwioLpVUzfzkPqkd3ABhzt1aXGw=,iv:HNoZfLhE6YqEbLGKXWgpw1NmZZK8Ij34ehcf9WRYFj8=,tag:Xp78jpvJM0By6GL0VtI6Mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
