---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - folders.yaml
  - alert-rules-pods.yaml
  - alert-rules-resources.yaml
  - alert-rules-infrastructure.yaml
